### ISSUE TITLE
[lat] Dialect specifications

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#143]
Add "Classical", "Ecclesiastical", and "Vulgar" specifications for Latin.

**Comment by kylebgorman** [comment]
Not directly related but the Latin extractor is also picking up pronunciations from other languages, like [this Spanish one](https://en.wiktionary.org/wiki/grammatica#Pronunciation_3).

**Comment by lfashby** [comment]
> Not directly related but the Latin extractor is also picking up pronunciations from other languages, like [this Spanish one](https://en.wiktionary.org/wiki/grammatica#Pronunciation_3).

That's quite an interesting problem. It looks to me like the root of the problem is in how the pron selector is defined, in particular how `following-sibling` as defined [here](https://github.com/kylebgorman/wikipron/blob/master/wikipron/extract/lat.py#L67) works. 
The first following-sibling `<ul>` of:
```
<h3>
  <span class="mw-headline" id="Etymology_2">Etymology 2</span>
  ...
</h3>
```
(which is the element that satisfies: `//{heading}[span[@class = "mw-headline" and @id = "{tag}"]]`) is the `<ul>` containing the Spanish pronunciation.

Here is a [snippet of code](https://gist.github.com/lfashby/e940644e31f8caa8f0fc18d7e7666236) I use to test the extraction functions, it is crude but allows you to test how an extraction function works on a particular entry (specified by providing the Wiktionary URL for that entry).

**Comment by kylebgorman** [comment]
Thanks for that. I'm really bad at reasoning about these so perhaps I can
convince somebody else to tackle this.
