### ISSUE TITLE
Language generator not honoring UTF8

### ISSUE THREAD

**Issue by agutkin** [kylebgorman/wikipron#167]
Running `codes.py` turns the following section in `languages.js`:
```
            "hanoi": "Hà Nội",
            "hcmc": "Hồ Chí Minh City",
            "hue": "Huế",
            "tc": "Vinh, Thanh Chương",
            "ht":"Hà Tĩnh"
```
into
```
            "hanoi": "H\u00e0 N\u1ed9i",
            "hcmc": "H\u1ed3 Ch\u00ed Minh City",
            "hue": "Hu\u1ebf",
            "tc": "Vinh, Thanh Ch\u01b0\u01a1ng",
            "ht": "H\u00e0 T\u0129nh"
```

**Comment by kylebgorman** [comment]
Starting [here](https://github.com/kylebgorman/wikipron/blob/master/data/wikipron/src/codes.py#L178)
we just need to add `ensure_ascii=False` to prevent that escaping.

Actually, both of those should absolutely be calls to the much faster `dump` (which takes a file handle as an argument and generates on the fly) rather than `dumps`. `dumps` is almost always a mistake.
