### ISSUE TITLE
[fre] /z/ given as pronunciation for œufs

### ISSUE THREAD

**Issue by ajmalanoski** [kylebgorman/wikipron#208]
I noticed while looking through `fre_phonemic.tsv` that /z/ is (erroneously) given as a pronunciation for *œufs*, probably because /z/ appears elsewhere on [the page](https://en.wiktionary.org/wiki/%C5%93ufs). This could potentially be an issue for other languages as well. 

I've noticed that when Wiktionary gives a word's IPA, it is generally preceded by the string "IPA(key):" . Perhaps this could be used to distinguish a word's transcription from other instances of IPA on the page?

**Comment by kylebgorman** [comment]
Maybe we should tighten the selectors to require it to come after that IPA string @ajmalanoski mentions.

**Comment by lfashby** [comment]
Thanks for submitting this! This might be a difficult one to resolve. I believe this occurs because we grab the whole `<li>` [here](https://github.com/kylebgorman/wikipron/blob/c905047339c0f2e5c4a0e1fe0c0e17701bd2009f/wikipron/config.py#L18). Tightening the selector or perhaps even changing the [yield_pron](https://github.com/kylebgorman/wikipron/blob/c905047339c0f2e5c4a0e1fe0c0e17701bd2009f/wikipron/extract/core.py#L24) function could certainly resolve this, but the consequences of manipulating the selector or `yield_pron` may be difficult to predict.

**Comment by kylebgorman** [comment]
I'm going to close this and mark it wontfix for now. Maybe some day we can come back to this.

**Comment by ajmalanoski** [comment]
(thumbs up)
