### ISSUE TITLE
[fre] Aspirated <h> not included in transcriptions

### ISSUE THREAD

**Issue by ajmalanoski** [kylebgorman/wikipron#212]
Wiktionary does not mark [aspirated <h>](https://en.wikipedia.org/wiki/Aspirated_h) in its transcriptions for French, instead adding a note before the transcription indicating whether a word-initial <h> is aspirated or mute, as on [this page](https://en.wiktionary.org/wiki/haricot#French). This distinction is phonologically relevant – although <h> is silent, words that start with an aspirated <h> behave as though they start with a consonant – so it probably should be included in our transcriptions, right?

**Comment by kylebgorman** [comment]
You're asking the right kind of question... _h-aspire_ is the kind of thing that ought to be in a true phonemic transcription of a word but... I am not surprised that it isn't present here. We don't catch specialty tags like that superscript "aspirated h" that you see on the page for _haricot_, and if we did, say just for French, what would we add to the phonemic transcription? Would you instead give it as /ha.ʁi.ko/? I don't know...there be dragons.

**Comment by ajmalanoski** [comment]
Most bilingual dictionaries I've seen use an apostrophe or something similar (e.g. /'aʁiko/), and the Wikipedia article on it says that French dictionaries mark it with an asterisk (e.g. /*aʁiko/). Of course, neither choice is standard IPA, but I suppose we could add a note in the phones file to explain.

**Comment by kylebgorman** [comment]
I am vaguely opposed to adding non-IPA signs, since that would likely break
other tools and require language-specific interpretation notes. Is there an
IPA alternative?

I think in this case we may have to acknowledge that this tool is really
only generating citation pronunciations; it doesn’t handle sandhi phenomena
(which this is: we don’t have any other liaison information here either)
nor is it obvious how to make it do so without substantially enriching the
spec.

**Comment by kylebgorman** [comment]
I'm going to close this for now. We can reopen if we ever figure out what the right thing to do is. I think this might be a simple enhancement to WikiPron (cf. Lucas's scripts to grab frequency data) but not part of WikiPron itself.
