### ISSUE TITLE
Plural words are missing

### ISSUE THREAD

**Issue by xburelle** [kylebgorman/wikipron#252]
For example, in french, "marronniers" does not appear but "marronnier" did. 
It can be useful to have all the forms of words.
May be it is the same for the verbs, with conjugation.

**Comment by jacksonllee** [comment]
Hi @xburelle, the entry page for [marronniers](https://en.wiktionary.org/wiki/marronniers) does not contain any pronunciation information. Given the goals of WikiPron (i.e., to retrieve pronunciation info as directly available on Wiktionary, not predict it for entries without it), the only way to solve this issue is for entries like this on Wiktionary to actually contain some pronunciation so that WikiPron can target these entries. The upstream Wiktionary data is being expanded by the community over time, so perhaps some of these entries may show up after the next round of WikiPron scraping!

**Comment by kylebgorman** [comment]
@xburelle if you want to predict pronunciations, check out [our recent shared task](https://www.aclweb.org/anthology/2020.sigmorphon-1.2/), which includes French models,
or the [associated baseline models](https://github.com/sigmorphon/2020/tree/master/task1).
