### ISSUE TITLE
Many words are missing in the Spanish dictionary

### ISSUE THREAD

**Issue by MiClobiMC** [kylebgorman/wikipron#414]
The Spanish dictionary is not complete, there are many words missing

**Comment by kylebgorman** [comment]
Yes, that's true but obviously so: no dictionary is complete. This is not the kind of thing we consider a bug with WikiPron, since it is just a tool to obtain pronunciation data from Wiktionary. If there are words that you'd like to see covered, add them and their pronunciations to Wiktionary and we'll include your contributions in the next release.
