### ISSUE TITLE
[yue] Cantonese support

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#57]
[yue] is ISO 693-3 only, but should be handled by [languagecodes.py](https://github.com/kylebgorman/wikipron/blob/master/wikipron/languagecodes.py) in the same way that [nci] for Classical Nahuatl and [hbs] for Serbo-Croatian are. 

Nonetheless, [yue] pulls nothing in phonetic and phonemic modes and does not even seem to begin scraping.

**Comment by jacksonllee** [comment]
The reasons why WikiPron v0.1.1 doesn't work for Cantonese:
1. The entries under "Cantonese" on Wiktionary all use the Jyutping romanization as the head word (see [here](https://en.wiktionary.org/wiki/Category:Cantonese_terms_with_IPA_pronunciation)), which means all the entries have a numeral (which denotes tone).
2. Because WikiPron [skips entries where the head word has a numeral](https://github.com/kylebgorman/wikipron/blob/cf0e54787cf301436003436583fd80ef1cc28c82/wikipron/config.py#L185-L187), all Cantonese entries are simply skipped.

Interestingly, the entries under "Chinese" instead use the Chinese characters as the head word, and have the IPA transcriptions for various Chinese languages, including Cantonese (e.g., check out [this entry](https://en.wiktionary.org/wiki/%E9%A6%99%E6%B8%AF#Chinese) for "Hong Kong"). To scrape for Cantonese, perhaps we should target these entries under "Chinese" on Wiktionary and get the head word (= Chinese characters) as the "graphemes", and then narrow down to the Cantonese IPA pronunciation as the phonemes. (Targeting the romanization as the graphemes would be rather uninteresting for G2P...)

That being said, getting Cantonese data through WikiPron (as described in the previous paragraph) is probably not our priority right now, as the data would be less relevant for grapheme-to-phoneme modeling but more about romanization / de-romanization (is this a word?).

**Comment by kylebgorman** [comment]
After talking with @lfashby I'm now convinced that the Latin and Japanese issue and the Cantonese/Chinese/Khmer/Thai issue are fundamentally the same---`Config` needs to be able to inspect `self.language` and return the appropriate selectors for both grapheme and phoneme.

**Comment by jacksonllee** [comment]
#277 checked in the code to handle the scraping of Cantonese data, but we have yet to actually get the Cantonese TSV files.

**Comment by kylebgorman** [comment]
I just reinstalled from HEAD and I'm getting an unrelated issue:

```
(base) [src]$ ./scrape.py --restriction=yue
Traceback (most recent call last):
  File "./scrape.py", line 224, in <module>
    main(parser.parse_args())
  File "./scrape.py", line 147, in main
    with open(LANGUAGES_PATH, "r", encoding="utf-8") as source:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kbg/.anaconda/lib/python3.7/site-packages/data/src/languages.json'
```

It seems that the path constants assume I'm working within a module called `data` in site-packages? I must have missed this change but it certainly does not work. Anyways, I would recommend just retrying that `./scrape.py` command until it goes through.

**Comment by kylebgorman** [comment]
I'm running this right now on a home server (granted, very much a low-power one, but this is usually an IO-bound process) and I'm noticing that impressionistically it's slower (in terms of how long it takes to find each batch of 100 or so prons) than other languages. Just noting here in case that's useful debug information.
