### ISSUE TITLE
[scraping] duplicate entries

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#81]
For various reasons we get true duplicate entries (i.e., same graphemic form, same phonemic form) in the big scrape. For example I I don't think this is exactly a bug; this could arise if our processing of the graphemic and/or phonemic form causes a duplicate pair to be formed.

Example: [phonemic Icelandic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/ice_phonemic.tsv) has 77 duplicates.

Two possible solutions:

1. We keep a `set` of the pairs as we go. If we find a pair already in the set, we don't print it.
2. Perhaps we just keep the last form and don't repeat it---this assumes the data is already sorted, which is not obviously correct.
3. We just apply `sort | uniq` to every TSV file at the end of the big scrape (can turn this into a simple Bash script and add it to the README.

I think (3) is but could be persuaded.

**Comment by lfashby** [comment]
Here is one example of how we form a duplicate through case-folding that I've run into. 

In the German phonemic tsv:
https://github.com/kylebgorman/wikipron/blob/80107984162f9ef91eab88d8d56ce88246a1d9fa/languages/wikipron/tsv/ger_phonemic.tsv#L117-L119
[117 on Wiktionary](https://en.wiktionary.org/wiki/aber#German) and [119 on Wiktionary](https://en.wiktionary.org/wiki/Aber#German)

If we go with solution 3 above, then I'd like to take a crack at writing the Bash script. If I'm understanding solution 2 correctly, then it would fail to filter out line 119 because it would only compare it to 118.

**Comment by jacksonllee** [comment]
+1 for option 3 (for having a post-processing script to remove duplicate entries)

**Comment by kylebgorman** [comment]
Yeah. It can arise from grapheme processing, phonemic processing, or both.

Sounds good, do the Bash script, Lucas. I think it'll be very short.

**Comment by lfashby** [comment]
Since I'm quite inexperienced with Bash I thought I'd check in here before attempting to resolve this issue with a pull request.

I wrote a simple script in languages/wikipron/src that, as far as I can tell, takes care of the duplicates. 
```
cd ../tsv/
for lang_tsv in *
do
    extension=${lang_tsv#*.}
    # Filter out README.md
    if [ $extension == "tsv" ]
    then
        echo "Sorting ${lang_tsv}"
        sort -u -t $"\t" -k1 -o $lang_tsv $lang_tsv
    fi
done
```
As I understand it, this will sort mostly by comparing the words, but will compare the transcriptions if the words are the same.

**Comment by kylebgorman** [comment]
On Fri, Nov 1, 2019 at 4:53 PM Lucas Ashby <notifications@github.com> wrote:

> Since I'm quite inexperienced with Bash I thought I'd check in here before
> attempting to resolve this issue with a pull request.
>
> I wrote a simple script in languages/wikipron/src that, as far as I can
> tell, takes care of the duplicates.
>
A few notes inline.

Use: `#!/bin/bash` on the first line and also set `set -eou pipefail` below
that.


> cd ../tsv/
>
>
`cd`ing to a directory is not something I'd recommend. Just add it to the
path for the wildcard below.

> for lang_tsv in *
> do
>
> These should go on the same line, and the variable name should be in all
caps:

     for TSV in tsv/*.tsv; do
         ...
     done

>
>     extension=${lang_tsv#*.}
>     # Filter out README.md
>     if [ $extension == "tsv" ]
>     then
>         echo "Sorting ${lang_tsv}"
>         sort -u -t $"\t" -k1 -o $lang_tsv $lang_tsv
>
>
Instead of filtering, just use a better wildcard---see above.

The sorting procedure will be fast enough that I don't think it's worth
"logging" with echo even.

I don't think this is guaranteed to work without overwriting the file. To
be sure create a temporary file and them move it over $TSV, thus:

       local -r TMPFILE=$(mktemp -t XXXXX.tsv)
       sort -u "${TMPFILE}" "${TSV}"
       mv "${TMPFILE}" "${TSV}"
    done

You finally don't need a fancy sort logic. We want to merge identical lines
only. If the line isn't identical we don't merge it. That's exactly what
`sort -u` already does. No need to have primary and secondary keys.

K

**Comment by lfashby** [comment]
Shouldn't I be able to get away with this?
```
#!/bin/bash
set -eou pipefail

for TSV in ../tsv/*.tsv; do
    sort -u -o "${TSV}" "${TSV}"
done
```
The [sort man page](https://ss64.com/bash/sort.html) states:
>   -o OUTPUT-FILE
>      Write output to OUTPUT-FILE instead of standard output.  If
>      OUTPUT-FILE is one of the input files, 'sort' copies it to a
>      temporary file before sorting and writing the output to
>      OUTPUT-FILE.

I think the temporary file creation and overwriting takes place internally.

**Comment by kylebgorman** [comment]
If it says so, then yes, thanks for actually reading the man page ;)
